name: Markdown Link Checker
on:
  push:
    branches:
      - main  # Триггер для push в ветку main
  pull_request:
    branches:
      - main  # Триггер для pull request в ветку main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'mlc_config.json'
        folder-path: 'Documents'
        max-depth: 2
