name: Markdown Link Checker and Metadata Validator

on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch

jobs:
  check:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository content

    - name: Install markdown-link-check
      run: |
        npm install -g markdown-link-check  # Install markdown-link-check

    - name: Check links in markdown files
      run: |
        markdown-link-check '**/*.md'  # Check all markdown files for broken links

    - name: Check metadata in markdown files
      run: |
        # Check for missing metadata
        # We are looking for a line that matches "Version: <version_number>"
        grep -L 'Version: ' **/*.md > missing_metadata_files.txt
        if [ -s missing_metadata_files.txt ]; then
          echo "The following markdown files are missing the 'Version' metadata:"
          cat missing_metadata_files.txt
          exit 1  # Fail the pipeline if any file is missing the version metadata
        else
          echo "All markdown files contain version metadata."
        fi
