name: Markdown Link Checker and Metadata Validator

on:
  push:
    branches:
      - main  # Триггер для push в ветку main
  pull_request:
    branches:
      - main  # Триггер для pull request в ветку main

jobs:
  check:
    runs-on: ubuntu-latest  # Используем последний Ubuntu для работы

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: Install markdown-link-check
      run: |
        npm install -g markdown-link-check  # Устанавливаем markdown-link-check через npm

    - name: Check links in markdown files
      run: |
        markdown-link-check 'Documents/**/*.md'  # Ищем .md файлы внутри папки Documents

    - name: Check metadata in markdown files
      run: |
        # Пользовательский скрипт для проверки отсутствующих метаданных
        # Ищем строки с "Version: <номер_версии>"
        grep -L 'Version: ' Documents/**/*.md > missing_metadata_files.txt
        if [ -s missing_metadata_files.txt ]; then
          echo "Следующие markdown файлы не содержат метаданные 'Version':"
          cat missing_metadata_files.txt
          exit 1  # Пайплайн завершится с ошибкой, если файл не содержит метаданных
        else
          echo "Все markdown файлы содержат метаданные версии."
        fi
